coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
        flags:
          - unit
        paths:
          - "src"
    patch:
      default:
        target: auto
        threshold: 100%
        base: auto
