import KeyInfo, { KeyLayout, normalizeLayout } from "./keyinfo";

const PET: KeyLayout = normalizeLayout("CommodorePet", [
  [
    ["@", "At"],
    ["!", "Exclamation"],
    ['"', "DoubleQuote"],
    ["#", "Hash"],
    ["$", "Dollar"],
    ["%", "Percent"],
    ["'", "Apostrophe"],
    ["&", "Ampersand"],
    ["\\", "Backslash"],
    ["(", "LeftParen"],
    [")", "RightParen"],
    ["<-", "LeftArrow"],
    ["[", "LeftBracket"],
    ["]", "RightBracket"],
  ],
  [
    {
      label: ["OFF", "RVS"],
      width: 1.5,
      key: "Reverse",
    },
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    ["^", "UpArrow"],
    ["<", "LessThan"],
    [">", "GreaterThan"],
  ],
  [
    {
      label: ["SHIFT", "LOCK"],
      offset: 1 / 3,
      width: 1.5,
      key: "ShiftLock",
    },
    "A",
    "S",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    [":", "Colon"],
    ["RUN", "STOP"],
    {
      label: "RETURN",
      width: 1.5,
      key: "Return",
    },
  ],
  [
    {
      label: "SHIFT",
      offset: 1 / 3,
      width: 2,
      key: "LShift",
    },
    "Z",
    "X",
    "C",
    "V",
    "B",
    "N",
    "M",
    [",", "Comma"],
    [";", "Semicolon"],
    ["?", "Question"],
    {
      label: "SHIFT",
      width: 2,
      key: "RShift",
    },
  ],
  [
    {
      label: "",
      width: 8 + 5 / 6,
      offset: 3,
      key: "Space",
    },
  ],
]);

export default PET;
