on: [push]

name: noentiendo CI

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check syntax
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build for desktop
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM module
        run: wasm-pack build

      - name: Build Webpack app
        run: |
          cd www
          npm install
          npm run build

      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Run tests and collect coverage
        run: LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' RUSTFLAGS="-Cinstrument-coverage -Clink-dead-code" cargo test

      - name: Install coverage tools (llvm-tools-preview)
        run: rustup component add llvm-tools-preview

      - name: Install coverage tools (grcov)
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      - name: Generate coverage report
        run: ./grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage/lcov.info

      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/coverage/lcov.info

      - name: Copy files
        run: |
          mkdir pages
          cp -r www/dist/* pages
          cp -r target/doc pages
          cp -r target/coverage pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          folder: pages
